export const headerTitles = [
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Solar Roof",
  "Solar Panels",
  "Powerwall",
  "Shop",
  "Account",
  "Menu",
];
export const sideBarItemsMobile = [
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Solar Roof",
  "Solar Panels",
  "Powerwall",
  "Existing Inventory",
  "Used Inventory",
  "Trade-In",
  "Demo Drive",
  "Insurnace",
  "Fleet",
  "Commercial Energy",
  "Utilities",
  "Charging",
  "Careers",
  "Find Us",
  "Events",
  "Support",
  "Investor Relations",
  "Shop",
  "Account",
  "More",
];

export const sideBarItemsDesktop = [
  "Existing Inventory",
  "Used Inventory",
  "Trade-In",
  "Demo Drive",
  "Insurance",
  "Fleet",
  "Cybertruck",
  "Roadster",
  "Semi",
  "Charging",
  "Commercial Energy",
  "Utilities",
  "Careers",
  "Find Us",
  "Events",
  "Support",
  "Investor Relations",
];
export const sideBarItemsMobileMore = [
  'Cybertruck',
  'Roadster',
  'Semi',
  'News'
];
